# Generated by Django 3.2.15 on 2024-01-26 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='address',
            new_name='name',
        ),
    ]
