# Generated by Django 3.2.15 on 2024-01-20 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_auto_20240120_1453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productorder',
            old_name='amount',
            new_name='quantity',
        ),
    ]
