# Generated by Django 3.2.15 on 2024-01-25 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_productorder_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Принят', 'Принят'), ('Собирается', 'Собирается'), ('Доставляется', 'Доставляется'), ('Доставлен', 'Доставлен')], default='Принят', max_length=20, verbose_name='Статус'),
        ),
    ]
