# Generated by Django 3.2.15 on 2024-01-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0048_auto_20240126_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(blank=True, choices=[('Электронно', 'Электронно'), ('Наличностью', 'Наличностью')], db_index=True, max_length=20, null=True, verbose_name='Способ оплаты'),
        ),
    ]
