# Generated by Django 3.2.15 on 2024-01-26 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0049_order_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.CharField(blank=True, choices=[('Электронно', 'Электронно'), ('Наличностью', 'Наличностью')], db_index=True, max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
