# Generated by Django 3.2.15 on 2024-02-04 16:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0055_delete_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorder',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена на момент заказа'),
        ),
    ]
