# Generated by Django 3.2.15 on 2024-02-12 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0057_alter_productorder_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('Электронно', 'Электронно'), ('Наличностью', 'Наличностью'), ('Не указано', 'Не указано')], db_index=True, default='Не указано', max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
