# Generated by Django 3.2.15 on 2024-02-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0058_alter_order_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorder',
            name='quantity',
            field=models.PositiveIntegerField(db_index=True, verbose_name='Количество продукта'),
        ),
    ]
